### ISSUE TITLE
Outdated example

### ISSUE THREAD

**Issue by jee1mr** [docusign/docusign-code-examples#2]
Hi, 
The examples are outdated (at least the nodejs one). I tried fixing all the syntax to latest and made it functional. But then I'm getting an error response from your server with not much explanation. Could you help me with this?

This is the response I'm getting on calling `evelopesApi.createEnvelope()`.
Status Code: 400
Text:  ` {"errorCode": "UNSPECIFIED_ERROR",  "message": "Non-static method requires a target."}`

**Comment by LarryKlugerDS** [comment]
Hi,

I'm sorry you're having this problem. Can you provide your updates as either a Pull Request or within your forked repo? I can then take a look at it. Also, do you know which example had the problem? Did any of the examples work?

Many thanks,

Larry Kluger
DocuSign

**Comment by Ergin008** [comment]
Hi @jee1mr, 

The Node client was refactored from version 2.x.x to 3.x.x.  For instance, to create an envelope in V2: 

`envDef.setEmailSubject('Please sign this document sent from Node SDK');`

whereas to create an envelope in V3: 

`envDef.emailSubject = 'Please sign this document sent from Node SDK';`

Can you confirm you are using the v3 syntax in your code?  Also, not sure if just a editing error in your comment or your code is actually like this but you have a typo in your example:

`evelopesApi.createEnvelope().`

Notice the mis-spelling on the **envelopesApi** object.

**Comment by jee1mr** [comment]
Yup. I'm using 3.xx I believe. And I've fixed all the syntax. `evelopesApi.createEnvelope() `was a typo here. Sorry about that. 
Let me send a pull request.

**Comment by jee1mr** [comment]
Hi. Did something change over the past few days? 
https://www.docusign.com/developer-center/api-overview 
IIRC had completely different content. And that's where I picked up the wrong examples from. But unable to find them now. Anyway, the newer examples seem fine. Thanks. 
Closing this issue.

**Comment by Ergin008** [comment]
Hi, yes we did update our developer center website recently sorry for any confusion that may have caused.  Good to hear the new samples are working, of course let us know if you come across any new issues etc.  Cheers
